cluster_name: Ansible_automation
ssh_key_path: /home/test/.ssh/id_rsa
nodes:
    - address: 192.168.6.103 
      user: test
      role:
        - controlplane
        - etcd
        - worker
      port: 2222
      docker_socket: /var/run/docker.sock
ignore_docker_version: false
enable_cri_dockerd: true
kubernetes_version: v1.25.9-rancher2-1
services:
    etcd:
      # Custom uid/guid for etcd directory and files
      uid: 52034
      gid: 52034
    kube-api:
      service_cluster_ip_range: 10.43.0.0/16
      service_node_port_range: 30000-32767
      pod_security_policy: false
      secrets_encryption_config:
        enabled: true
      audit_log:
        enabled: true
        configuration:
          max_age: 6
          max_backup: 6
          max_size: 110
          path: /var/log/kube-audit/audit-log.json
          format: json
          policy:
            apiVersion: audit.k8s.io/v1 
            kind: Policy
            omitStages:
              - "RequestReceived"
            rules:
              - level: RequestResponse
                resources:
                - group: ""
                  resources: ["pods"]
    kube-controller:
      cluster_cidr: 10.42.0.0/16
      service_cluster_ip_range: 10.43.0.0/16
      extra_args:
        feature-gates: RotateKubeletServerCertificate=true
        cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
        cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 10.43.0.10
      fail_swap_on: true
      pod-infra-container-image: "k8s.gcr.io/pause:3.2"

      extra_args:
        max-pods: 250
        feature-gates: RotateKubeletServerCertificate=true

network:
  plugin: canal
  mtu: 1400
  options:
    canal_iface: enp4s0
    canal_flannel_backend_type: vxlan
    canal_autoscaler_priority_class_name: system-cluster-critical
    canal_priority_class_name: system-cluster-critical

monitoring:
  provider: metrics-server

ingress:
  provider: nginx
  node_selector:
    app: ingress
